backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - label: "Store"
    name: "store"
    editor:
      preview: false
    files:
      - label: "Products List"
        name: "products-list"
        file: "content/serve/products.json"
        fields:
          - label: Product
            name: product
            widget: list
            fields:
              - {label: Name, name: name, widget: 'string'}
              - {label: ID, name: id, widget: 'string'}
              - {label: 'Description', name: 'desc', widget: 'text'}
              - {label: 'Price', name: 'price', widget: 'number'}
              - {label: 'Picture', name: 'pic', widget: 'image'}
              - {label: 'Unit', name: 'unit', widget: 'string'}

      - label: "Packages List"
        name: "packages-list"
        file: "content/serve/packages.json"
        fields:
          - label: Package
            name: package
            widget: list
            fields:
              - {label: Name, name: name, widget: 'string'}
              - {label: ID, name: id, widget: 'string'}
              - {label: 'Description', name: 'desc', widget: 'text'}
              - {label: 'Price', name: 'price', widget: 'number'}
              - {label: 'Picture', name: 'pic', widget: 'image'}
              - {label: 'Unit', name: 'unit', widget: 'string'}
      
      - label: "Shipping Options"
        name: "shipping"
        file: "content/serve/shipping.json"
        fields:
          - label: Shipping
            name: shipping
            widget: list
            fields:
              - {label: 'Type', name: 'label', widget: 'string'}
              - {label: 'Name', name: 'value', widget: 'string'}
              - {label: 'Cost', name: 'cost', widget: 'number'}

      - label: "Announcements"
        name: "announcements"
        file: "content/serve/announcements.json"
        fields:
          - label: Post
            name: post
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: 'Message', name: 'message', widget: 'string'}
              - {label: 'Date', name: 'date', widget: 'date'}
              
